#:schema node_modules/wrangler/config-schema.json
# wrangler.toml
name = 'cf-create-worker'
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "224f4ea4-29ef-46ea-8faf-02673bb8480c"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://twikoo.r2.890809.xyz"

[dev]
port = 5000
